/*************************************************************************
 * Version      Date            Name                    Description
 * ======================================================================
 * V1.0       14-02-2021        Developer1             Add Method implemented 
 * 
 ************************************************************************/
public with sharing class Calculator {
    public Calculator() {
    }
    
       
}